---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Ensure unzip is installed
  become: yes
  apt:
    name: unzip
    state: present
    update_cache: yes


- name: Download AWS CLI v2 installer with curl
  become: yes
  shell: |
    curl -o /tmp/awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  args:
    creates: /tmp/awscliv2.zip

- name: Unzip AWS CLI v2 installer
  become: yes
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes

- name: Install AWS CLI v2
  become: yes
  command: /tmp/aws/install
  args:
    creates: /usr/local/bin/aws


- name: Login to AWS ECR
  shell: |
    aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin 028892270743.dkr.ecr.{{ aws_region }}.amazonaws.com
  args:
    executable: /bin/bash

- name: Pull Docker images
  shell: |
    docker pull {{ item.image }}
  loop: "{{ docker_images }}"

- name: Remove existing container if present
  community.docker.docker_container:
    name: "{{ item.container_name }}"
    state: absent
  loop: "{{ docker_images }}"


- name: Ensure Docker containers are running with latest image
  community.docker.docker_container:
    name: "{{ item.container_name }}"
    image: "{{ item.image }}"
    state: started
    ports:
      - "{{ item.port }}"
    recreate: yes
  when: >
    (inventory_hostname == groups['ec2_instances'][0] and item.container_name == 'container1') or
    (inventory_hostname == groups['ec2_instances'][1] and item.container_name == 'container2')
  loop: "{{ docker_images }}"
