---
- name: Check if node is already joined to the cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- name: Copy join script to worker
  copy:
    src: "{{ playbook_dir }}/join-command.sh"
    dest: /tmp/join-command.sh
    mode: "0755"

- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- name: Join worker to cluster
  command: sh /tmp/join-command.sh
  become: yes
  when: not kubelet_conf_stat.stat.exists
  register: join_result
  changed_when: "'This node has joined the cluster' in join_result.stdout"

- name: Show join status
  debug:
    msg: "{{ 'Joined successfully' if 'joined' in join_result.stdout else 'Join failed: ' + join_result.stderr }}"
  when: not kubelet_conf_stat.stat.exists