all:
  hosts:
    master:
      ansible_host: <master_public_ip>
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /path/to/your/private_key.pem
    worker1:
      ansible_host: <worker1_public_ip>
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /path/to/your/private_key.pem
    worker2:
      ansible_host: <worker2_public_ip>
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /path/to/your/private_key.pem
    worker3:
      ansible_host: <worker3_public_ip>
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /path/to/your/private_key.pem
  children:
    master_group:
      hosts:
        master:
    worker_group:
      hosts:
        worker1:
        worker2:
        worker3:
